#!/bin/sh
#
# post-install: update all glib schemas, icon cache & desktop database

/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
/usr/bin/gtk4-update-icon-cache -q -t -f /usr/share/icons/hicolor
/usr/bin/update-desktop-database -q /usr/share/applications

#EOF
