#!/bin/sh
#
# post-install: install/update all glib schemas & update icon cache

/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
/usr/bin/gtk-update-icon-cache /usr/share/icons/hicolor

#EndOfFile